/**
 * Real Robinhood positions view — the bridge file marked to market.
 *
 * Options are marked at the cached CBOE chain mid (per-contract $ = mid×100);
 * equities at the live quote. Unrealized = side-signed (current − cost) — a
 * leg or share line with no mark shows null rather than a fake zero, and the
 * summary counts how much of the book is actually marked. Realized totals are
 * whatever the bridge pull recorded (RH realized-P&L endpoints).
 */
import type { FastifyInstance } from 'fastify'
import { readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { loadRhPositions, rhAgeHours, type RhOptionLeg } from '../api/rhPositions.js'
import { getOptionChain, getQuote } from '../api/marketdata.js'
import { buildRhStructures } from '../engine/rhStructures.js'
import type { OptionContract } from '../api/types.js'

const CACHE_DIR = process.env.AI_CACHE_DIR
  ? resolve(process.env.AI_CACHE_DIR)
  : resolve(process.cwd(), 'cache')
const STRATEGY_PNL_FILE = join(CACHE_DIR, 'rh-strategy-pnl.json')

export type RhLegView = RhOptionLeg & {
  /** Current per-contract value from the chain mid ($, positive); null = no mark. */
  mark: number | null
  /** Side-signed unrealized $ for the whole leg (qty included); null = no mark. */
  unrealized: number | null
}

export type RhEquityView = {
  sym: string
  qty: number
  avgCost: number
  last: number | null
  unrealized: number | null
}

const keyOf = (exp: string, strike: number, type: string) => `${exp}|${strike}|${type}`

export async function rhRoutes(app: FastifyInstance) {
  /** Per-strategy realized track record (iron condor vs wheel vs directional),
   *  generated by a Claude-session pull from RH order history — the engine
   *  just serves the file; regenerate by asking Claude to refresh. */
  app.get('/api/rh/strategy-pnl', async (_req, reply) => {
    try {
      return JSON.parse(readFileSync(STRATEGY_PNL_FILE, 'utf8'))
    } catch {
      reply.code(404)
      return { error: 'no rh-strategy-pnl file — 在 Claude 里说"刷新策略战绩"生成' }
    }
  })

  app.get('/api/rh/positions', async (_req, reply) => {
    const p = loadRhPositions()
    if (!p) {
      reply.code(404)
      return { error: 'no rh-positions bridge file — 在 Claude 里说"刷新持仓"生成' }
    }

    // --- Options: mark at chain mid ---
    const pairs = [...new Set(p.optionLegs.map((l) => `${l.sym}|${l.expiration}`))]
    const contracts = new Map<string, OptionContract>()
    await Promise.all(pairs.map(async (pair) => {
      const [sym, exp] = pair.split('|')
      try {
        const chain = await getOptionChain(sym, exp)
        for (const c of chain) contracts.set(`${sym}|${keyOf(c.expiration, c.strike, c.optionType)}`, c)
      } catch { /* legs of this pair stay unmarked */ }
    }))

    let optionsUnrealized = 0
    let optionsMarked = 0
    const optionLegs: RhLegView[] = p.optionLegs.map((l) => {
      const c = contracts.get(`${l.sym}|${keyOf(l.expiration, l.strike, l.optionType)}`)
      const mid = c && c.mid > 0 ? c.mid : null
      if (mid == null) return { ...l, mark: null, unrealized: null }
      const mark = mid * 100
      // avgCost is signed (long paid > 0, short credit < 0); current side-signed
      // value is +mark for long / −mark for short → unrealized = current − cost.
      const currentSigned = l.side === 'long' ? mark : -mark
      const unrealized = (currentSigned - l.avgCost) * l.qty
      optionsUnrealized += unrealized
      optionsMarked++
      return { ...l, mark, unrealized }
    })

    // --- Structures: pair legs, attach tasty-style management alerts ---
    const optionSyms = [...new Set(p.optionLegs.map((l) => l.sym))]
    const spots = new Map<string, number>()
    await Promise.all(optionSyms.map(async (sym) => {
      try {
        const q = await getQuote(sym)
        if (q.last > 0) spots.set(sym, q.last)
      } catch { /* alerts degrade to no-ITM-check */ }
    }))
    const structures = buildRhStructures(optionLegs, spots)

    // --- Equities: mark at live quote ---
    let equityUnrealized = 0
    let equityQuoted = 0
    const equities: RhEquityView[] = await Promise.all(p.equities.map(async (e) => {
      try {
        const q = await getQuote(e.sym)
        if (!(q.last > 0)) throw new Error('no quote')
        const unrealized = (q.last - e.avgCost) * e.qty
        equityUnrealized += unrealized
        equityQuoted++
        return { ...e, last: q.last, unrealized }
      } catch {
        return { ...e, last: null, unrealized: null }
      }
    }))

    return {
      fetchedAt: p.fetchedAt,
      ageHours: rhAgeHours(),
      account: p.account,
      optionLegs,
      structures,
      optionsUnrealized,
      optionsMarked,
      equities,
      equityUnrealized,
      equityQuoted,
      realized: p.realized ?? null
    }
  })
}
